### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by Heimdallr-1**
I've updated to the latest version with the original text and updated the names of the items and characters to match occultism. For now, I'll do it as a draft. After a full check of the translation in the game, there will be some edits.

### CODE REVIEW

**Comment by Heimdallr-1** [comment]
"What's "book.occultism.dictionary_of_spirits.getting_started.first_ritual.intro.title": "Ritual **(tm)**"

**Comment by klikli-dev** [comment]
> "What's "book.occultism.dictionary_of_spirits.getting_started.first_ritual.intro.title": "Ritual **(tm)**"

it's just a silly joke - "(tm)" to pretend "The Ritual" is trademarked ;)

**Comment by Heimdallr-1** [comment]
I knew it! :D

**Comment by klikli-dev** [comment]
Sorry @Heimdallr-1 I completely missed the notification that the PR is ready!

**Comment by Heimdallr-1** [comment]
**If there are any additional changes to the localization, please write them here.**

**Pull request merged**
