### PR TITLE
Update en_us.json

### PR DESCRIPTION
**Pull request by MuteTiefling**
Found a couple grammatical errors that ought to be corrected.

Use "an" instead of "a" when the following word begins with a vowel sound. "An Afrit" instead of "A Afrit"

Fixed some missing capitalization. Generally in the book spirit types are written as proper nouns (Foliot instead of foliot).

For Lime Chalk the title felt out of place compared to the others, so it was made "refreshing" as lime drinks are refreshing.

Orange Chalk title changed. At the very least this would be "Hot Little" not "Little Hot". 

Green Chalk title similarly felt out of place, like it couldn't decide. Settled to "Chalk of the Wilds".

Light Blue chalk title changed to Glacial Chalk. Glaced is not a word in English. 

Following the "Spirit Summoning" format for summoning rituals, the others are changed to "Spirit Possession" and "Spirit Infusion" for consistency and clarity. In the case of possession, the spirit is possessing the object or creature. As written, it meant the spirit was being possessed by the object or creature. 

There are a few more in there for clarity's sake. Feel free to ask if you have any questions on why they were changed.

### CODE REVIEW

**Comment by Eqis-Edu** [comment]
Thanks, starting to move to datagen so as not to be overwritten

The green is really to convey this feeling of not fitting in, as it is the first chalk outside the main line of progression.

**Comment by MuteTiefling** [comment]
> The green is really to convey this feeling of not fitting in, as it is the first chalk outside the main line of progression.

An understandable desire, but the text doesn't read that way. "This, but specifically this other thing entirely" is confusing and contradictory. "Specifically" denotes precision. It is 'exactly' this thing. So presenting another name and immediately changing it just confuses things.

**Comment by Eqis-Edu** [comment]
I still don't see the confusion, "Nature" is a very big concept and explaining the "Flora" aspect is not contradictory.

**Comment by MuteTiefling** [comment]
This is X.

No that's a lie. It's actually Y.

It just makes no sense in English and not conveying the meaning you're intending. Just call it what it is the first time.

It's a title in an instruction manual. It should be clear and concise. What benefit or added understanding is there by naming it two different things?

It's a common tendency to write like we speak,and what you've got here is something you'd do in conversation. Start by stating a broad concept, then second guessing yourself and refining what you have to say.

In writing there's no need for that. You're not talking to us. So skip straight to the refined thought. The confusion isn't "I have no idea what you're saying", it's simply that the writing doesn't seem to know what _it_ is saying.

**Comment by Eqis-Edu** [comment]
Now I get your point, I just put "The Plant Chalk"

**Comment by klikli-dev** [comment]
@Eqis-Edu @MuteTiefling are all changes from this PR now in #1237?

**Comment by MuteTiefling** [comment]
I've left some comments and a review on that one @klikli-dev.

Looks like some writing style mistakes were missed. 

Also, I'm questioning the final pentagram's use of nearly (or completely) invisible blocks. This just feels very anti player to me and is going to lead to an endless stream of people who can't complete it.

**Comment by klikli-dev** [comment]
> I've left some comments and a review on that one @klikli-dev.
> 
> Looks like some writing style mistakes were mixed.
> 
> Also, I'm questioning the final pentagram's use of nearly (or completely) invisible blocks. This just feels very anti player to me and is going to lead to an endless stream of people who can't complete it.

I'll leave this one open until we have all cleaned up.

Eqis reported the invisible blocks as a bug on modonomicon which I have to investigate, because that really should not happen. Independent of that we may have to change the recipe in occultism until that is fixed or just find a good alternative fit

**Comment by MuteTiefling** [comment]
Tbh they feel rather out of place and random for an end game pentacle used to summon eldritch beings. 

I think there are more thematic blocks that could be used instead.

**Comment by klikli-dev** [comment]
Closing this in favor of #261 to collect the remaining open issues with recent changes there

**Comment by klikli-dev** [comment]
Apparently I did not in fact close it ...

**Pull request closed without merging**
