### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by Heimdallr-1**
I just **added** a new translation for some of the sentences and made some text _corrections_. **Here's my question**: Is it possible to modify ENUSProvider.java to support the Russian language or make it translatable to Russian?

### CODE REVIEW

**Comment by klikli-dev** [comment]
> I just **added** a new translation for some of the sentences and made some text _corrections_. **Here's my question**: Is it possible to modify ENUSProvider.java to support the Russian language or make it translatable to Russian?

@Heimdallr-1 thanks! Good question - yes, we can! the best option is to copy ENUSProvider.java, name it e.g. RURUProvider, also rename the class name in the file, then set the language it provides to "ru_ru". After that the texts can be replaced in the file.

It might be possible to semi-automate that with regex (that is what I did for ENUSProvider when I created it from the existing english .json) or maybe something like chatgpt could even automatically do it if we provide it the json + the enusprovider as reference (with instructions to update the texts?)

**Comment by klikli-dev** [comment]
I am leaving the PR open for now so we have a place to discuss this

**Comment by Heimdallr-1** [comment]
Okay, so what do I need to do?

**Comment by klikli-dev** [comment]
I can add the required java class for you then the only thing that remains is to copy over the translations again (default will be english).

Can you enable write access for maintainers (me) on this pull request so I can push the change to your fork?
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Heimdallr-1** [comment]
I think it would have been easier to just click 'Allowing edits by maintainers' and sort of be done with it.

**Comment by Heimdallr-1** [comment]
You know, I didn't figure out how to give you access, especially since you did a merge.

**Comment by klikli-dev** [comment]
@Heimdallr-1 Apologies, I forgot about that! I am not sure how giving access works specifically I only read the above github.

I've created the language provider here: https://github.com/klikli-dev/occultism/tree/feat/ruru-langgen

What is left now is to replace the english texts with the russian translation that is currently in the .json file - as far as I know the only way to do that is to do it manually once.
In the future we can always modify the ruruprovider

**Comment by klikli-dev** [comment]
@Heimdallr-1 I just merged the latest translation features in to that branch.
Basically my plan is to move all Book related translations in to the OccultismBookProvider. 
Currently about 50% is still in the ENUSProvider, but I already removed them from RURU.

I added an example to OccultismBookProvider.makeDictionaryOfSpirits() on how to translate book texts:
```java
helper.book("dictionary_of_spirits");
this.lang().add(helper.bookName(), "Dictionary of Spirits");
this.lang().add(helper.bookTooltip(), "An introduction to the spirit world.");
this.lang("ru_ru").add(helper.bookName(), "Словарь душ");
this.lang("ru_ru").add(helper.bookTooltip(), "Введение в мир духовных практик.");
```

Note the this.lang("ru_ru")

All the non-book texts can be translated directly in RURUProvider

**Comment by Heimdallr-1** [comment]
Understood

**Pull request merged**
