### PR TITLE
Trials & Possessions

### PR DESCRIPTION
**Pull request by Eqis-Edu**
+ Refactor "SummonWildHuntRitual" to "SummonWildRitual" to have more types of greater spirits, the wilds
-> Allow use "summon_number" to specifie the quantity of spawner entitys

+ Possessed Hoglin always drop something 
-> Empty pool changed to: Piglin Banner Patter or Pigstep Music Disc or Nether brick (equal chances)

+ Added "Horde" possessions variation, use te  "SummonWildRitual" to get items like: 
-> All Music disks; 
-> All Armors trims;
-> All Pottery sherd; 
-> Banner pattern (Snout, Flow, Guster);
-> Others "rare" items, normally get via world exploration. (like Sniffer Egg)
(Note: the Wild Armor Template Trim is not dropped, but crafted using ritual)
(Note²: “All” considers previous possessions)
+ Enemy Hordes: Husk (desert theme), Drowned (ocean theme), Creeper (disks) and Silverfish (ruins theme)

+ Added 3 tier of Possessed Breeze, the high will drop Heavy Core.

+ Added ritual to turn Vex into Allay

### CODE REVIEW

**Comment by klikli-dev** [comment]
That is huge! I'll check it out later today or tomorrow!

**Comment by ffuentesm** [comment]
I would also suggest to also add the normal Hoglin drops to the Possessed Hoglin in case. So you get leather and some pork in case nothing drops.

**Comment by Eqis-Edu** [comment]
> I would also suggest to also add the normal Hoglin drops to the Possessed Hoglin in case. So you get leather and some pork in case nothing drops.

I thought about it, but it would effectively reduce the cost of the ritual, and that is not the intention (except for netherite scrap, when return it is to lost only time and low cost material). The goal is really a "punitive" reward percentage

**Comment by ffuentesm** [comment]
I see, still the ritual page should tell about all the possible drops, or show the other optional drops from the ritual, not just the smithing template. Have the items rotate to show the options.
image

**Comment by Eqis-Edu** [comment]
I don't know if EMI or JEI can switch results (I only know about ingredients using tags), to see a visual way for all possibilities I use JER which shows the mob's loot table (not yet in 1.21). Anyway, in the Spirits Dictionary all results are described in text

**Comment by ffuentesm** [comment]
I am not sure about results like this. 
But I know that at least on the crafting side, you can use Ingredient lists instead of a tag. This is what the new Demon Dream Essence uses, so instead of a 2 recipe display, it shows a single recipe with two item variants. You need to use [ ] in the output to convert it into a list.

**Comment by klikli-dev** [comment]
> I am not sure about results like this. But I know that at least on the crafting side, you can use Ingredient lists instead of a tag. This is what the new Demon Dream Essence uses, so instead of a 2 recipe display, it shows a single recipe with two item variants. You need to use [ ] in the output to convert it into a list.

The outputs do not support this. I think EMI/JEI would, but the underlying recipe system does not (output = item stack).
Occultism uses a custom "recipe result" with multiple outputs for miners, but that comes with hefty drawbacks, and is required for the functionality, not the rendering.

I believe that relying on emi/jei addons for drops is better, then clicking "r" will show the entity.
Alternatively the custom text for the output item could be extended to list all possible drops, however that does not integrate with the "r" function of JEI/EMI

**Pull request merged**
